src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $contents;

    /**
     * @ORM\ManyToOne(targetEntity=Posts::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $post;

    /**
     * @ORM\Column(type="datetime")
     */
    private $posted_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContents(): ?string
    {
        return $this->contents;
    }

    public function setContents(string $contents): self
    {
        $this->contents = $contents;

        return $this;
    }

    public function getPost(): ?Posts
    {
        return $this->post;
    }

    public function setPost(?Posts $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeInterface
    {
        return $this->posted_at;
    }

    public function setPostedAt(\DateTimeInterface $posted_at): self
    {
        $this->posted_at = $posted_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=PostsRepository::class)
 */
class Posts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contents;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modificated_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_public;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(
     *     maxSize = "22048k",
     *     mimeTypes = {"image/jpeg"},
     *     mimeTypesMessage = "Proszę załaduj plik w formacje JPEG"
     * )
     */
    private $photo_path;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="post", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Ratings::class, mappedBy="post", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $ratings;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContents(): ?string
    {
        return $this->contents;
    }

    public function setContents(?string $contents): self
    {
        $this->contents = $contents;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModificatedAt(): ?\DateTimeInterface
    {
        return $this->modificated_at;
    }

    public function setModificatedAt(?\DateTimeInterface $modificated_at): self
    {
        $this->modificated_at = $modificated_at;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(?bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function getPhotoPath(): ?string
    {
        return $this->photo_path;
    }

    public function setPhotoPath(?string $photo_path): self
    {
        $this->photo_path = $photo_path;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ratings[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Ratings $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setPost($this);
        }

        return $this;
    }

    public function removeRating(Ratings $rating): self
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getPost() === $this) {
                $rating->setPost(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Posts;
use App\Entity\User;
use App\Entity\Ratings;
use App\Form\CommentsType;
use App\Service\SendEmialToUserService;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Session\Session;
use App\Service\DeleteEntitiesService;
use Symfony\Component\HttpFoundation\Response;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="main")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $postsData = $em->getRepository(Posts::class)->findBY(['is_public' => true], ['created_at' => 'DESC']);
        $ratingsData = $em->getRepository(Ratings::class)->findBy(['post' => $postsData]);

        return $this->render('main/index.html.twig', [
            'postsData' => $postsData,
            'ratingsData' => $ratingsData,
        ]);
    }

    /**
     * @Route("/user_panel", name="user_panel")
     */
    public function userPanel()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('main/user_panel.html.twig', []);
    }


    /**
     * @Route("/post_details/{id}", name="post_details")
     */
    public function postDetails(int $id, Request $request)
    {
        $newComment = new Comments();

        $em = $this->getDoctrine()->getManager();
        $post = $em->getRepository(Posts::class)->findOneBY(['id' => $id]);
        $ratingsData = $em->getRepository(Ratings::class)->findBY(['post' => $post]);
        $commentsData = $em->getRepository(Comments::class)->findBY(['post' => $post]);

        $form = $this->createForm(CommentsType::class, $newComment);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $em = $this->getDoctrine()->getManager();
                $newComment->setPostedAt(new \DateTime());
                $newComment->setPost($post);
                $newComment->setUser($this->getUser());
                $em->persist($newComment);
                $em->flush();
                $this->addFlash('success', 'Dodano komentarz');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Wystąpił nieoczekiwany błąd');
            }

            return $this->redirectToRoute('post_details', ['id' => $post->getId()]);
        }

        return $this->render('main/post_details.html.twig', [
            'post' => $post,
            'ratingsData' => $ratingsData,
            'commentForm' => $form->createView(),
            'commentsData' => $commentsData,
        ]);
    }

    /**
     * @Route("/user_details/{username}", name="user_details")
     */
    public function userDetails($username)
    {
        $em = $this->getDoctrine()->getManager();
        $userData = $em->getRepository(User::class)->findOneBY(['username' => $username]);
        $userPosts = $em->getRepository(Posts::class)->findBY(['user' => $userData->getId(), 'is_public' => true]);
        $userComments = $em->getRepository(Comments::class)->findBY(['user' => $userData->getId()]);
        $userRatings = $em->getRepository(Ratings::class)->findBY(['user' => $userData->getId()]);

        return $this->render('main/user_comments_posts_details.html.twig', [
            'userPosts' => $userPosts,
            'userData' => $userData,
            'userComments' =>  $userComments,
            'userRatings' =>  $userRatings,
        ]);
    }

    /**
     * @Route("/user_details_auth/", name="user_details_auth")
     */
    public function userDetailsAuth(): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $em = $this->getDoctrine()->getManager();
        $userData = $em->getRepository(User::class)->findOneBY(['id' => $this->getUser()]);
        $userPosts = $em->getRepository(Posts::class)->findBY(['user' => $userData->getId()]);
        $userComments = $em->getRepository(Comments::class)->findBY(['user' => $userData->getId()]);
        $userRatings = $em->getRepository(Ratings::class)->findBY(['user' => $userData->getId()]);

        return $this->render('main/user_comments_posts_details_auth.html.twig', [
            'userPosts' => $userPosts,
            'userData' => $userData,
            'userComments' =>  $userComments,
            'userRatings' =>  $userRatings,
        ]);
    }

    /**
     * @Route("/user_panel/send_email/{user}", name="app_send_mail_to_user") 
     */
    public function sendEmailToUser($user, SendEmialToUserService $SendEmialToUserService)
    {
        $em = $this->getDoctrine()->getManager();
        try {
            $SendEmialToUserService->sendMailToUser($user, $em);
            $this->addFlash('success', 'Wysłano ponownie link aktywacyjny');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Wystąpił nieoczekiwany błąd');
        }
        return $this->redirectToRoute('user_panel');
    }

    /**
     * @Route("/user_panel/remove_account/{user}", name="remove_account") 
     */
    public function removeUserAccount($user, DeleteEntitiesService $deleteEntitiesService)
    {
        $filesystem = new Filesystem();
        $catalogPath = 'download/' . $this->getUser()->getId() . '/';
        $em = $this->getDoctrine()->getManager();
        try {
            $user = $em->getRepository(User::class)->find($user);
            $posts = $em->getRepository(Posts::class)->findBy(['user' => $user]);
            $comments = $em->getRepository(Comments::class)->findBy(['user' => $user]);
            if ($this->getUser()->getId() == $user->getId()) {
                $session = $this->get('session');
                $session = new Session();
                $session->invalidate();
            }
            foreach ($posts as $post) {
                $filesystem->remove([$catalogPath . $post->getPhotoPath()]);
            }
            $deleteEntitiesService->deleteEntities($em, $comments);
            $deleteEntitiesService->deleteEntities($em, $posts);

            $em->remove($user);
            $em->flush();
            $this->addFlash('success', 'Usunięto konto z systemu');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Wystąpił nieoczekiwany błąd');
        }
        return $this->redirectToRoute('app_login');
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	Strona główna
{% endblock %}

{% block body %}
	<!-- Main Content -->
	{% for post in postsData %}
		<div class="post-preview">
			<a href="{{ path('post_details', {'id' : post.id }) }}">
				<h2 class="post-title">
					{{ post.title}}
				</h2>
				<h3 class="post-subtitle">
					{{ post.contents|striptags |length > 75 ? post.contents|striptags |slice(0, 75)  ~ '...' : post.contents|striptags }}
				</h3>
			</a>
			<p class="post-meta">Zamieszczone przez
				<a href="{{ path('user_details', {'username' : post.user.username }) }}">{{ post.user.username }}</a>
				,
				{{ post.createdAt|date('d.m.Y H:i:s') }}<br>
				Komentarze:
				{{ post.comments|length }},
				{% set sumPositive = 0 %}
				{% set sumNegative = 0 %}
				{% for rating in ratingsData %}
					{% if post.id == rating.post.id  %}
						{% set sumPositive = sumPositive + rating.positive %}
						{% set sumNegative = sumNegative + rating.negative %}
					{% endif %}
				{% endfor %}
				Oceny:
				<em style='color:green;'>{{ sumPositive }}</em>
				<em style='color:red;'>{{ sumNegative }}</em>
			</p>
		</div>
		<hr>
	{% endfor %}
	<hr>
{% endblock %}

templates/main/post_details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	Post
{% endblock %}

{% block header %}

	<header class="masthead" style="background-image: url({{ asset('download/')}}{{ post.user.id }}/{{ post.photoPath }})">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					<div class="post-heading">
						<h1>{{ post.title }}</h1>
						<span class="meta">Zamieszczone przez
							<a href="{{ path('user_details', {'username' : post.user.username }) }}">{{ post.user.username }}</a>
							{{ post.createdAt|date('d.m.Y H:i:s') }}</span>
					</div>
				</div>
			</div>
		</div>
	</header>
{% endblock %}
{% block body %}
	<article>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					{{ post.contents|raw }}
				</div>
			</div>
		</div>
	</article>
	<hr>
	{% if not app.user %}
		<div class='alert alert-danger'>Uwaga ! Funkcjonalność serwisu dostępna tylko dla zalogowanych użytkowników.</div>
	{% elseif app.user.isVerified == false %}
		<div class='alert alert-danger'>Uwaga ! Twoje konto nie zostało zweryfikowane, nie masz dostępu do tej funkcjonalności serwisu.</div>
	{% else %}
		<div class="post-preview text-center">
			<h2>Oceny</h2>
			{% set sumPositive = 0 %}
			{% set sumNegative = 0 %}
			{% for rating in ratingsData %}
				{% set sumPositive = sumPositive + rating.positive %}
				{% set sumNegative = sumNegative + rating.negative %}
			{% endfor %}
			<button style='color:green;font-size:40px' onclick="window.location.href='{{ path('post_vote' , { 'id': post.id , 'type' : 'p', 'value' : '1'}) }}'">{{  ratingsData == null ? '0' : sumPositive }}<img src="{{ asset('assets/vendor/jumpicon/iconfinder-thumb-up.png')}}"></button>
			<button style='color:red;font-size:40px' onclick="window.location.href='{{ path('post_vote' , { 'id': post.id , 'type' : 'n', 'value' : '1'}) }}'">{{  ratingsData == null ? '0' : sumNegative }}<img src="{{ asset('assets/vendor/jumpicon/iconfinder-thumb-down.png')}}"></button>
		</div>
		<hr>
		<div class="post-preview text-center">
			<h2>Komentarze</h2>
			{% for comment in commentsData %}
				<span class="meta">
					{{ comment.contents|raw }}
					Dodane przez
					<a href="{{ path('user_details', {'username' : comment.user.username }) }}">{{ comment.user.username }}</a>
					,
					{{ comment.postedAt|date('d.m.Y H:i:s') }}</span>
				<hr>
			{% endfor %}
			{% form_theme commentForm 'bootstrap_4_layout.html.twig' %}
			{{ form_start(commentForm) }}
			{{ form_row(commentForm.contents) }}
			{{ form_row(commentForm.submit) }}
			{{ form_end(commentForm) }}
		{% endif %}
	</div>
{% endblock %}

templates/main/user_comments_posts_details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }} Szczegóły {{ userData.username }}
{% endblock %}

{% block body %}
<h1>Szczegóły użytkownika: {{ userData.username }}</h1><br>

{% set sumPositive = 0 %}
{% set sumNegative = 0 %}
{% for rating in userRatings %}
	{% set sumPositive = sumPositive + rating.positive %}
	{% set sumNegative = sumNegative + rating.negative %}
{% endfor %}
<h1>Oddanych głosów <em style='color:green;'>{{ sumPositive }}</em> <em style='color:red;'>{{ sumNegative }}</em> </h1><br>

<h1>Lista postów</h1>
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">tytuł</th>
			<th scope="col">data</th>
		</tr>
	</thead>
	<tbody>
		{% for post in userPosts %}
			<tr>
				<td>{{ loop.index }}</td>
				<td>
					<a href="{{ path('post_details', {'id' : post.id }) }}">{{ post.title }}<a/></td>
				</td>
				<td>{{ post.createdAt|date('d.m.Y H:i:s') }}
				</td>
			</tr>
		</td>
	</tbody>
</tr>{% endfor %}</tbody></table><br>

<h1>Lista komentarzy</h1>
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">tytuł posta</th>
			<th scope="col">komentarz</th>
			<th scope="col">data</th>
		</tr>
	</thead>
	<tbody>
		{% for comment in userComments %}
			<tr>
				<td>{{ loop.index }}</td>
				<td>
					<a href="{{ path('post_details', {'id' : comment.post.id }) }}">{{ comment.post.title }}<a/></td>
				</td>
				<td>
					{{ comment.contents|striptags |length > 25 ? comment.contents|striptags |slice(0, 25)  ~ '...' : comment.contents|striptags }}</td>
				</td>
				<td>{{ comment.postedAt|date('d.m.Y H:i:s') }}</td>
	</tbody>
	{% endfor %}
</table><br>


{% endblock %}

templates/main/user_comments_posts_details_auth.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }} Konto {{ userData.username }}
{% endblock %}

{% block body %}

{% set sumPositive = 0 %}
{% set sumNegative = 0 %}
{% for rating in userRatings %}
	{% set sumPositive = sumPositive + rating.positive %}
	{% set sumNegative = sumNegative + rating.negative %}
{% endfor %}
<h1>Oddanych głosów <em style='color:green;'>{{ sumPositive }}</em> <em style='color:red;'>{{ sumNegative }}</em> </h1><br>

<h1>Lista postów</h1>
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">tytuł</th>
			<th style='width: 20px'></th>
			<th style='width: 20px'></th>
			<th style='width: 15px'></th>
		</tr>
	</thead>
	<tbody>
		{% for post in userPosts %}
			<tr>
				<td>{{ loop.index }}</td>
				<td>
					<a href="{{ path('post_details', {'id' : post.id }) }}">{{ post.title }}<a/></td>
				</td>
				<td>
					<a href="{{ path('post_edit' , { 'id': post.id }) }}" class="btn btn-success">Edycja</a>
				</td>
				<td>
					<a href="{{ path('post_delete' , { 'id': post.id }) }}" class="btn btn-danger">Usuń</a>
				</td>
				<td>
					{% if post.isPublic == '1' %}
						<input type="checkbox" checked data-toggle="toggle" data-onstyle="outline-success" data-offstyle="outline-danger" onchange="window.location.href='{{ path('post_set_visibility' , { 'id': post.id , 'visibility' : '0'}) }}'"></td>
				{% else %}
					<input type="checkbox" data-toggle="toggle" data-onstyle="outline-success" data-offstyle="outline-danger" onchange="window.location.href='{{ path('post_set_visibility' , { 'id': post.id , 'visibility' : '1'}) }}'"></td>
				{% endif %}
				</td>	
			</tr>
		{% endfor %}
	</tbody>
</table><br>

<h1>Lista komentarzy</h1>
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">tytuł posta</th>
			<th scope="col">komentarz</th>
			<th scope="col">data</th>
			<th style='width: 20px'></th>
			<th style='width: 20px'></th>
		</tr>
	</thead>
	<tbody>
		{% for comment in userComments %}
			<tr>
				<td>{{ loop.index }}</td>
				<td>
					<a href="{{ path('post_details', {'id' : comment.post.id }) }}">{{ comment.post.title }}<a/></td>
				</td>
				<td>
					{{ comment.contents|striptags |length > 25 ? comment.contents|striptags |slice(0, 25)  ~ '...' : comment.contents|striptags }}</td>
				</td>
				<td>{{ comment.postedAt|date('d.m.Y H:i:s') }}</td>
				<td>
					<a href="{{ path('comment_edit' , { 'id': comment.id }) }}" class="btn btn-success">Edycja</a>
				</td>
				<td>
					<a href="{{ path('comment_delete' , { 'id': comment.id }) }}" class="btn btn-danger">Usuń</a>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table><br>


{% endblock %}

templates/main/user_panel.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	Panel Użytkownika
{% endblock %}

{% block body %}
	{% if app.user.isVerified == false %}
		<div class='alert alert-danger'>Uwaga ! Twoje konto nie zostało zweryfikowane, nie będziesz miał dostępu do funkcjonalności serwisu.</div>
	{% endif %}
	<h1>Panel Użytkownika
	</h1>
	<a class="btn btn-lg btn-primary" href="{{ relative_path('/reset-password')}}">Zmiana hasła</a>
	<br><br>
	<button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#exampleModal">
		Usuwanie konta
	</button>

	<br><br>
	{% if app.user.isVerified == false %}
		<a class="btn btn-lg btn-primary" href="{{ path('app_send_mail_to_user', {'user' : app.user.id }) }}">Wyślij ponownie link aktywacyjny</a>
	{% endif %}
{% endblock %}